# Generated by Django 5.1.7 on 2025-04-08 05:34

import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="GameState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("choosing", "Choosing"),
                            ("listening", "Listening"),
                            ("answering", "Answering"),
                            ("finished", "Finished"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "time_left",
                    models.IntegerField(
                        blank=True, db_default=None, default=None, null=True
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, db_default=None, default=None, null=True
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, db_default=None, default=None, null=True
                    ),
                ),
                (
                    "current_melody_id",
                    models.IntegerField(
                        blank=True, db_default=None, default=None, null=True
                    ),
                ),
                (
                    "choosing_player_id",
                    models.IntegerField(
                        blank=True, db_default=None, default=None, null=True
                    ),
                ),
                (
                    "answering_player_id",
                    models.IntegerField(
                        blank=True, db_default=None, default=None, null=True
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        blank=True,
                        db_default=None,
                        default=None,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "last_action",
                    models.DateTimeField(
                        db_default=datetime.datetime(2025, 4, 8, 10, 34, 46, 202765),
                        default=datetime.datetime(2025, 4, 8, 10, 34, 46, 202765),
                    ),
                ),
                (
                    "delete_at",
                    models.DateTimeField(
                        blank=True, db_default=None, default=None, null=True
                    ),
                ),
                (
                    "answered_players_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        db_default=None,
                        default=None,
                        null=True,
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuessTheMelodyGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="game_app.category",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game_app.guessthemelodygame",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Melody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(db_default=0, default=0)),
                ("name", models.CharField(max_length=255)),
                ("link", models.CharField(max_length=255)),
                ("is_guessed", models.BooleanField(db_default=False, default=False)),
                (
                    "game_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game_app.gamecategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(db_default=0, default=0)),
                ("nickname", models.CharField(max_length=255)),
                ("is_master", models.BooleanField(db_default=False, default=False)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="game_app.guessthemelodygame",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(max_length=255)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game_app.guessthemelodygame",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game_app.player",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="player",
            constraint=models.UniqueConstraint(
                fields=("game", "nickname"), name="unique_game_nickname"
            ),
        ),
    ]
