# Generated by Django 5.1.7 on 2025-04-11 13:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('game_app', '0006_alter_gamecategory_game_alter_gamelink_game_and_more'),
	]

	operations = [
		migrations.AlterField(
			model_name='gamelink',
			name='player',
			field=models.OneToOneField(
				on_delete=django.db.models.deletion.CASCADE,
				related_name='link',
				to='game_app.player',
			),
		),
		migrations.AlterField(
			model_name='gamestate',
			name='last_action',
			field=models.DateTimeField(
				db_default=datetime.datetime(2025, 4, 11, 18, 22, 39, 882415),
				default=datetime.datetime(2025, 4, 11, 18, 22, 39, 882415),
			),
		),
	]
