# Generated by Django 5.1.7 on 2025-04-16 16:58

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('game_app', '0007_alter_gamelink_player_alter_gamestate_last_action'),
	]

	operations = [
		migrations.RemoveField(
			model_name='gamestate',
			name='last_action',
		),
	]
