# Generated by Django 5.1.7 on 2025-04-19 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_app", "0010_alter_gamelink_player"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="melody",
            name="game_category",
        ),
        migrations.AddField(
            model_name="category",
            name="game",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="game_app.guessthemelodygame",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="melody",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="melodies",
                to="game_app.category",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="GameCategory",
        ),
    ]
