# Generated by Django 5.1.7 on 2025-04-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_app", "0011_remove_melody_game_category_category_game_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="melody",
            name="link",
            field=models.TextField(),
        ),
    ]
