# Generated by Django 5.1.7 on 2025-04-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_app", "0012_alter_melody_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
